### ISSUE TITLE
error calling isset: unsupported type "invalid"

### ISSUE THREAD

**Issue by 2Dou** [halogenica/beautifulhugo#32] opened 2017-03-14 08:10 UTC
ERROR 2017/03/14 16:06:38 theme/partials/head.html template: theme/partials/head.html:56:13: executing "theme/partials/head.html" at <isset .Params.bigimg...>: error calling isset: unsupported type "invalid"
ERROR 2017/03/14 16:06:38 theme/partials/header_wp.html template: theme/partials/header_wp.html:13:8: executing "theme/partials/header_wp.html" at <isset $bigimg 0>: error calling isset: unsupported type "invalid"

**Comment by halogenica** [comment] 2017-03-17 04:20
Can you please explain this? What did you do that caused this? How can I reproduce it? to me it looks like it could have been caused by setting an invalid image name in the config.toml file. Can you delete all the [[Params.bigimg]] fields and tell me if the problem still occurs? The bigimg's seem to work correctly on the example website as-is.

**Comment by tamanugi** [comment] 2017-03-19 07:26
I also experienced a similar problem.

Although there was no problem when using version 0.19,
A similar error occurred when version 0.20dev was used.

I think this error has occurred due to the following change in version 0.20.
https://github.com/spf13/hugo/issues/3092

**Comment by halogenica** [comment] 2017-04-17 03:47
I think this is fixed now. Please feel free to give it a shot and let me know if it's not fixed. I tested with 0.20. I was looking for the particular change that I thought would have fixed it (I made it a while ago but couldn't test for sure because I wasn't able to reproduce the error at the time); but I couldn't find the exact commit that fixed it.

**Closed by halogenica** 2017-04-17 03:47 UTC
Labels: bug
