### ISSUE TITLE
Error building theme Hugo v0.49 relating to head.html

### ISSUE THREAD

**Issue by sgcullen** [halogenica/beautifulhugo#208] opened 2018-10-19 19:00 UTC
Getting an error when building the site with the latest version of Hugo.

Seems related to Line 5 in head.html partial.

Building sites … ERROR 2018/10/19 19:38:54 Error while rendering "taxonomyTerm" in "": template: _default/terms.html:3:5: executing "_default/terms.html" at <partial "head.html" ...>: error calling partial: template: partials/head.html:5:126: executing "partials/head.html" at <delimit ($.Scratch.G...>: error calling delimit: can't iterate over <nil>

**Comment by rootkea** [comment] 2018-10-20 15:40
Here is the complete log:  
```
$ hugo serve  -D --verbose
INFO 2018/10/20 21:09:21 Using config file: /home/rootkea/Documents/hacking/hugo/rootkea.me/config.toml
Building sites … INFO 2018/10/20 21:09:21 syncing static files to /
INFO 2018/10/20 21:09:22 found taxonomies: map[string]string{"tag":"tags", "category":"categories"}
INFO 2018/10/20 21:09:22 Alias "/tags/bigimg/page/1/index.html" translated to "tags/bigimg/page/1/index.html"
INFO 2018/10/20 21:09:22 Alias "/page/1/index.html" translated to "page/1/index.html"
INFO 2018/10/20 21:09:22 Alias "/tags/code/page/1/index.html" translated to "tags/code/page/1/index.html"
ERROR 2018/10/20 21:09:22 Error while rendering "taxonomyTerm" in "": template: _default/terms.html:3:5: executing "_default/terms.html" at <partial "head.html" ...>: error calling partial: template: partials/head.html:5:126: executing "partials/head.html" at <delimit ($.Scratch.G...>: error calling delimit: can't iterate over <nil>
WARN 2018/10/20 21:09:22 template: _default/terms.html:3:5: executing "_default/terms.html" at <partial "head.html" ...>: error calling partial: template: partials/head.html:5:126: executing "partials/head.html" at <delimit ($.Scratch.G...>: error calling delimit: can't iterate over <nil>
INFO 2018/10/20 21:09:22 Alias "/tags/markdown/page/1/index.html" translated to "tags/markdown/page/1/index.html"
INFO 2018/10/20 21:09:22 Alias "/tags/example/page/1/index.html" translated to "tags/example/page/1/index.html"
INFO 2018/10/20 21:09:22 Alias "/tags/math/page/1/index.html" translated to "tags/math/page/1/index.html"
INFO 2018/10/20 21:09:22 Alias "/page/page/1/index.html" translated to "page/page/1/index.html"
INFO 2018/10/20 21:09:22 Alias "/tags/photoswipe/page/1/index.html" translated to "tags/photoswipe/page/1/index.html"
INFO 2018/10/20 21:09:22 Alias "/post/page/1/index.html" translated to "post/page/1/index.html"
Total in 467 ms
Error: Error building site: logged 1 error(s)
$
```

BTW, 
```
$ hugo version
Hugo Static Site Generator v0.49.2/extended linux/amd64 BuildDate: 2018-10-11T09:57:02Z
$
```

**Comment by dancwilliams** [comment] 2018-10-21 00:58
I just upgraded my site to 0.49.2 and to the latest theme version to test this and did not have any issues.  I also have it active on Netlify at 0.49.2.

I wonder what feature I may not be activating that causes this...

Hugo Version:
```
Hugo Static Site Generator v0.49.2/extended darwin/amd64 BuildDate: unknown
```

Build:
```
Daniels-MacBook-Pro:networkhobo (update_theme *%)$ hugo server

                   | EN   
+------------------+-----+
  Pages            | 170  
  Paginator pages  |   2  
  Non-page files   |   8  
  Static files     |  83  
  Processed images |   8  
  Aliases          |  71  
  Sitemaps         |   1  
  Cleaned          |   0  

Total in 542 ms
Watching for changes in /Documents/git/networkhobo/{content,data,layouts,static,themes}
Watching for config changes in /Documents/git/networkhobo/config.toml
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

**Comment by rootkea** [comment] 2018-10-21 14:28
@dancwilliams 

> I wonder what feature I may not be activating that causes this...  

For starters, we are using `hugo` on different platforms. I'm guessing that you use Mac?

**Comment by sgcullen** [comment] 2018-10-22 12:57
Thanks for cleaning up the initial report - it was submitted in a hurry and was not totally complete.

I'm on 0.49.2 and the content at the moment is the example site content - not a full standard site so perhaps it's a difference between the example site causing the issue and the full production site you have @dancwilliams.

I've been away from hugo for a little bit so will have dive deeper to try and understand what's going on better.

**Comment by g4v4g4i** [comment] 2018-10-22 16:52
I have the same problem:

INFO 2018/10/22 18:47:28 found taxonomies: map[string]string{"category":"categories", "tag":"tags"}
ERROR 2018/10/22 18:47:28 Error while rendering "taxonomyTerm" in "": template: _default/terms.html:3:5: executing "_default/terms.html" at <partial "head.html" ...>: error calling partial: template: partials/head.html:5:126: executing "partials/head.html" at <delimit ($.Scratch.G...>: error calling delimit: can't iterate over <nil>
WARN 2018/10/22 18:47:28 template: _default/terms.html:3:5: executing "_default/terms.html" at <partial "head.html" ...>: error calling partial: template: partials/head.html:5:126: executing "partials/head.html" at <delimit ($.Scratch.G...>: error calling delimit: can't iterate over <nil>

**Comment by rootkea** [comment] 2018-10-23 12:11
@dancwilliams 

Thank you for reporting back the Linux build. :)

As @sgcullen noted, it looks like the example site is using some Hugo feature which isn't valid as per the latest Hugo version.

**Comment by rootkea** [comment] 2018-10-24 11:05
BTW, this has made "Demo" website to be unavailable at https://themes.gohugo.io/beautifulhugo/

**Comment by rootkea** [comment] 2018-10-24 15:01
This commit https://github.com/halogenica/beautifulhugo/commit/8014d6faa61d49fc6df8ac561ddc8d8bd440a3af introduced the issue. I'm no Go/Hugo expert so can't really point/fix the problem.

**Comment by sgcullen** [comment] 2018-10-24 16:38
Yes - it seems that `.Data.Terms.` (see [8014d6f](https://github.com/halogenica/beautifulhugo/commit/8014d6faa61d49fc6df8ac561ddc8d8bd440a3af) is returning an empty map object.

`delimit ( $.Scratch.Get "most_used" )` is then iterating over an empty object which it cannot do (on line 5.

Removing `.Data.Plural .Data.Singular ( delimit ( $.Scratch.Get "most_used" ) ", " ", and " ) | truncate 180` from line 5 of head.html will act as a quick fix to stop builds from failing.

I need to get my head around the taxonomy terms set up to be able to offer a true full fix.

**Comment by sweetppro** [comment] 2018-10-25 16:55
adding:
`preservetaxonomynames = "true"`
into my `config.toml `file fixes the crashing for me

**Comment by sweetppro** [comment] 2018-10-25 17:35
this fixes the crashing... although im having bigger problems, so can't be sure if its a real fix:
replace line 3 on `baseof.html` with this:
`{{ partial "head.html" (dict "head" . "terms" $) }}`

**Comment by halogenica** [comment] 2018-10-26 07:42
Thank you everyone for your bug reports! I checked in what I think should be a fix; please let me know if this works or doesn't work for you: cc4b60aa7dc621dbf6b2f84b08f27a94442353d1

**Comment by sgcullen** [comment] 2018-10-26 15:43
Thanks halogenica - that now works to fix that issue - thanks 👍

**Closed** 2018-10-26 17:59 UTC

**Comment by rootkea** [comment] 2018-10-27 10:46
@halogenica Thanks for fixing! While I can reproduce clean example site on `hugo server -D`, I still don't see `Demo` button besides `Download` at https://themes.gohugo.io/beautifulhugo/  

I assumed it was because the example site build failed but now I see no reason why the button is not displayed.
