### ISSUE TITLE
demo theme at hugo site messed up

### ISSUE THREAD

**Issue by tom-harvey** [halogenica/beautifulhugo#57] opened 2017-05-02 17:40 UTC
don't know where the problem is, but the demo site

   http://themes.gohugo.io/theme/beautifulhugo/

isn't displaying this theme properly when you click on the green demo button (firefox 53.0/mac) . i think they just rebuilt their theme showcase, so maybe the problem is over there...
UPDATE next day: the example site here builds and runs just fine, so the problem may be entirely over at https://themes.gohugo.io/theme/beautifulhugo/

**Comment by rayjolt** [comment] 2017-05-04 11:42
Sorry, this was totally my fault. The pull request referenced above explains what the problem is, and will fix it once it is merged. After that, the theme demo site should go back to normal the next time it is rebuilt. (We should probably request a rebuild ourselves, as our demo currently looks very broken.)

**Closed** 2017-05-04 16:43 UTC

**Comment by halogenica** [comment] 2017-05-04 16:44
No worries, thank you for root causing this! Would you mind requesting the rebuild @rayjolt?

**Comment by rayjolt** [comment] 2017-05-06 12:55
It seems it's already been done without me requesting it. The photoswipe gallery is still broken though. I had a go at fixing it, but I'm running into problems. The issue is in the figure shortcodes the gallery uses.

If I have a base URL of `http://localhost/themes/beautifulhugo`, the image URL should be `http://localhost/themes/beautifulhugo/img/hexagon.jpg`. However, with a shortcode of `{{< figure thumb="-thumb" link="/img/hexagon.jpg" >}}` the generated image URL is `http://localhost/img/hexagon.jpg`, and with a shortcode of `{{< figure thumb="-thumb" link="img/hexagon.jpg" >}}`, from the blog page the generated image URL is `http://localhost/post/2017-03-20-photoswipe-gallery-sample/img/hexagon.jpg`.

I can't think of a way to fix this that will work for all base URLs. Maybe this is something that needs to be dealt with in Hugo itself?

By the way, I found out that you can test how the site looks outside the domain root by using `hugo server --baseURL "http://localhost/theme/beautifulhugo/"`.
